run1:
	nameko run service1:SalesforceService --config config.yaml

run2:
	nameko run service2:SalesforceService --config config.yaml

run3:
	nameko run service3:SalesforceService --config config.yaml

run4:
	nameko run service4:SalesforceService --config config.yaml

run5:
	nameko run service5:SalesforceService --config config.yaml

run6:
	nameko run service6:SalesforceService --config config.yaml

run7:
	nameko run service7:SalesforceService --config config.yaml

run8:
	nameko run service8:SalesforceService --config config.yaml



